### ISSUE TITLE
can pypackage work with an already instantiated repo?

### ISSUE THREAD

**Issue by dfguerrerom** [12rambau/pypackage#129]
I'm creating some materials for a project that I want to be installable with a list of requirements, can I apply this template to my repo if it has already been initiated? should I start from scratch first?

**Comment by 12rambau** [comment]
I don't exactly know how `copier` behaves with an already existing project, I was planning to experiment on it myself with older projects that I would like to update. 

I'll do that after geo4good.

**Comment by 12rambau** [comment]
So to answer your question yes you can but it's a bit tedious. See the answer I received on copier-org discussions: https://github.com/orgs/copier-org/discussions/1393
